CREATE TABLE  service (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TEMPO INT NOT NULL,
    DATA TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
    DATA_ATUALIZACAO TIMESTAMP
);